server:
  port: 8080

spring:
  profiles:
    active: prod
  datasource:
    url: ${secrets.RDS_PATH}
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  jwt:
    secretKey: ${secrets.JWT_SECRET_KEY}
    expiration: 172800000    # 48시간
    refreshExpiration: 604800000   # 7일

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0 #사용하는 버전을 명시
    path: /v3/api-docs #api 문서 확인 경로, localhost:8080/v3/api-docs 로 접근
  default-consumes-media-type: application/json #기본으로 설정되는 미디어타입 지정
  auto-tag-classes: true
